export const actionTypes = {
  CONNECT_COMPONENT: 'MD_TRANSITION_CONNECT_COMPONENT',
  BODY_ELEMENT_CONNECT: 'MD_TRANSITION_BODY_ELEMENT_CONNECT',
  DISCONNECT_COMPONENT: 'MD_TRANSITION_DISCONNECT_COMPONENT',
  GROUP_WILL_UPDATE: 'MD_TRANSITION_GROUP_WILL_UPDATE',
  GROUP_DID_UPDATE: 'MD_TRANSITION_GROUP_DID_UPDATE',
  GROUP_GET_CHILD_REF: 'MD_TRANSITION_GROUP_GET_CHILD_REF',
  EVENT_RECORD_POSITION: 'MD_TRANSITION_EVENT_RECORD_POSITION',
  ANCHOR_GET_ELEM: 'MD_TRANSITION_ANCHOR_PREPARE_TRANS',
  COMMON_ELEMENT_GET_ELEM: 'MD_TRANSITION_COMMON_ELEMENT_GET_ELEM',
  DRAWER_GET_ELEM: 'MD_TRANSITION_DRAWER_GET_ELEM',
  TOOLBAR_GET_ELEM: 'MD_TRANSITION_TOOLBAR_GET_ELEM',
};

export const treeActionTypes = {
  CONNECT_COMPONENT: 'TREE_CONNECT_COMPONENT',
  DISCONNECT_COMPONENT: 'TREE_DISCONNECT_COMPONENT',
}

export const zoomPanActionTypes = {
  CONNECT_COMPONENT: 'ZOOM_PAN_CONNECT_COMPONENT',
  DISCONNECT_COMPONENT: 'ZOOM_PAN_DISCONNECT_COMPONENT',
  CORRECT_ELEM_RECT: 'ZOOM_PAN_CORRECT_ELEM_RECT',
}
